class Zebra {

    // ZPL Commands we might need
    deviceLanguageZPL = '! U1 setvar "device.languages" "zpl"';
    deviceLanguageLinePrint = '! U1 setvar "device.languages" "line_print"';
    resetDevice = '! U1 do "device.reset" ""';
    setReconnect = '! U1 setvar "bluetooth.enable_reconnect" "off"'; 
    discoverableOn = '! U1 setvar "bluetooth.discoverable" "on"';
    minimumSecurityMode = '! U1 setvar "bluetooth.minimum_security_mode" "1"';
    ping = 'ping';
    resetBuffer = '~JA';

    serviceUUID = 'xxxxx';
    characteristicUUID = 'xxxxx';
    
    ZEBRA_MAX_STRING_BUFFER_LENGTH = 250;
    ZEBRA_DEFAULT_LABEL_LENGTH = 600;

    namePrefix = 'xxxxxxx';

    /**
     * Dummy getter for POC
     * Fetch the command any way you find correct
     * @exampleString generated by: https://labelary.com/viewer.html 
     * @returns string
     */

    header() {
        return `
            ^XA

            ^LL300

            ^FX Label header
            ^CF0,40
            ^FO260,75^FHello world header^FS

            ^XZ
        `;
    }

    getZPLCommand(car) {
        return `
            ^XA

            ^LL700

            ^CFA,25
            ^FO50,70^FDHello world body^FS

            ^XZ
        `;
    }

}

export default Zebra;
